export enum NotificationStatus {
  CREATED = 'CREATED',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
}

export enum DeliveryStatus {
  CREATED = 'CREATED',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
}

export enum ChannelType {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  WHATSAPP = 'WHATSAPP',
  WEBHOOK = 'WEBHOOK',
  SLACK = 'SLACK',
  TEAMS = 'TEAMS',
}

export enum RecipientType {
  INTERNAL_USER = 'INTERNAL_USER',
  EXTERNAL_USER = 'EXTERNAL_USER',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
}

export enum AttemptResult {
  SUCCESS = 'SUCCESS',
  TRANSIENT_ERROR = 'TRANSIENT_ERROR',
  PERMANENT_ERROR = 'PERMANENT_ERROR',
}

export enum ProviderType {
  SES = 'SES',
  TWILIO = 'TWILIO',
  FCM = 'FCM',
  SENDGRID = 'SENDGRID',
  INFOBIP = 'INFOBIP',
}

export enum EventType {
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
  DELIVERY_QUEUED = 'DELIVERY_QUEUED',
  ATTEMPT_STARTED = 'ATTEMPT_STARTED',
  ATTEMPT_SUCCESS = 'ATTEMPT_SUCCESS',
  ATTEMPT_FAILED = 'ATTEMPT_FAILED',
  DELIVERY_SENT = 'DELIVERY_SENT',
  DELIVERY_DELIVERED = 'DELIVERY_DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  DLQ_ENTERED = 'DLQ_ENTERED',
}

export enum Platform {
  IOS = 'IOS',
  ANDROID = 'ANDROID',
  WEB = 'WEB',
}
